language: python

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9-dev"
  allow_failures:
    - python: "3.9-dev"

install:
  - pip install pytest
  - pip install responses
  - pip install pytest-cov
  - pip install coveralls
  - pip install requests
  - pip install pyjwt
  - pip install uuid

script:
  - pytest --cov=tests/

after_success:
  - coveralls