language: python
python:
  - "3"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  -
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=tests/
after_success:
  - coveralls